name: Steel
description: The implementation of the Flint minigame framework for the Bukkit Minecraft server mod.
version: 1.3.5
api-version: 1.13
author: Max Roncace
main: net.caseif.flint.steel.SteelMain
